apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
        - name: backend
          image: library-system-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: library-backend-config
          command:
            - sh
            - -c
            - PYTHONPATH=/app uvicorn main:app --host 0.0.0.0 --port 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
