apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-elasticsearch
  template:
    metadata:
      labels:
        app: library-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
          ports:
            - containerPort: 9200
          env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: es-data
          emptyDir: {}
        - name: es-config
          configMap:
            name: library-elasticsearch-config